### ISSUE TITLE
Build fails with patch applied

### ISSUE THREAD

**Issue by marvic2409** [h0tc0d3/linux_pgo#2]
When trying to apply this patch to the latest kernel I get the following build errors:

`vmlinux.o: warning: objtool: __llvm_prf_data+0x18: data relocation to !ENDBR: ibt_save+0x0`
`vmlinux.o: warning: objtool: __llvm_prf_data+0x18: data relocation to !ENDBR: ibt_restore+0x0`
`vmlinux.o: warning: objtool: __llvm_prf_data+0x18: data relocation to !ENDBR: cet_disable+0x0`
  `OBJCOPY modules.builtin.modinfo`
  `GEN     modules.builtin`
  `MODPOST Module.symvers`
  `CC      .vmlinux.export.o`
 ` UPD     include/generated/utsversion.h`
  `CC      init/version-timestamp.o`
  `LD      .tmp_vmlinux.btf`
`ld.lld: error: duplicate symbol: __llvm_profile_raw_version`
`>>>` `defined at usercopy_64.c`
`>>>``            vmlinux.o:(__llvm_profile_raw_version)`
`>>>` `defined at .vmlinux.export.c`
`>>> ` `          .vmlinux.export.o:(.rodata.__llvm_profile_raw_version+0x0)`
 ` BTF     .btf.vmlinux.bin.o`
`pahole: .tmp_vmlinux.btf: Invalid argument`
  `LD      .tmp_vmlinux.kallsyms1`
`ld.lld: error: .btf.vmlinux.bin.o: unknown file type`

usercopy_64.c isn't modified so I'm not sure why there seems to be issues coming from it. I am also compiling with the latest version of clang and my ld.lld is also the latest version

**Comment by h0tc0d3** [comment]
Probably the reason is that the work of the pgo profiler llvm and its profile format have changed in new versions LLVM. The patch only works with the specified versions of LLVM 14 and LLVM 13, LLVM 12 with an additional patches https://github.com/h0tc0d3/llvm-git from **005** to **008**. Unfortunately, I can’t help you, I do not provide free support for this patchset, and it was posted as is for an article about PGO.
